import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PrettiFlow",
  description: "Generated by PrettiFlow Agent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
        {/* Built by PrettiFlow Badge */}
        <div className="fixed bottom-4 right-4 z-50">
          <a 
            href="https://prettiflow.com" 
            target="_blank" 
            rel="noopener noreferrer"
            className="flex items-center gap-2 px-3 py-1.5 bg-gradient-to-br from-zinc-800 to-zinc-900 rounded-md shadow-lg shadow-black/50 border border-zinc-700/50 hover:from-zinc-700 hover:to-zinc-800 transition-all duration-200"
          >
            <div className="relative w-4 h-4">
              <Image
                src="/logo.svg"
                alt="PrettiFlow"
                width={16}
                height={16}
                className="brightness-110 "
              />
            </div>
            <span className="text-xs font-medium text-zinc-200 tracking-wide" style={{
              textShadow: '0 1px 2px rgba(255, 255, 255, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.15)'
            }}>
              Built on Prettflow
            </span>
            <div className="absolute inset-0 rounded-md bg-gradient-to-b from-white/10 to-transparent pointer-events-none" />
          </a>
        </div>
              <script src="/.pf/inspector-client.v13.js" defer></script>
        </body>
    </html>
  );
}
